const list = [
  {
    name: 'Dashboard',
    isCollapsible: false,
    open: false,
    link: '/dashboard',
    active: false,
    normalIcon: '/assets/images/menu/home.svg',
    activeIcon: '/assets/images/menu/home1.svg',
  },
  {
    name: 'Orders',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/bag.svg',
    activeIcon: '/assets/images/menu/bag1.svg',
    subMenu: [
      {
        name: 'All orders',
        subLink: '/allorders',
        count: 0,
        key: 'ALL_ORDERS',
      },
      {
        name: 'Pending orders',
        subLink: '/pendingorders',
        count: 0,
        key: 'PENDING_ORDERS',
      },
      {
        name: 'Rejected',
        subLink: '/rejectedorders',
        count: 0,
        key: 'REJECT_ORDERS',
      },
      {
        name: 'Cancelled',
        subLink: '/cancelledorders',
        count: 0,
        key: 'CANCEL_ORDERS',
      },
      {
        name: 'Processing',
        subLink: '/processingorders',
        count: 0,
        key: 'PROCESS_ORDERS',
      },
      {
        name: 'Ready to Pickup',
        subLink: '/readyorders',
        count: 0,
        key: 'READY_ORDERS',
      },
      // {
      //   name: 'Picked up Orders',
      //   subLink: '/pickeduporders',
      //   count: 0,
      //   key: 'PICKED_ORDERS',
      // },
      {
        name: 'Delivered',
        subLink: '/deliveredorders',
        count: 0,
        key: 'DELIVERY_ORDERS',
      },
      // {
      //   name: 'Refund initiated',
      //   subLink: '/refundinitiated',
      //   count: 0,
      //   key: 'RINITIATED_ORDERS',
      // },
      // {
      //   name: 'Refund processing',
      //   subLink: '/refundprocessing',
      //   count: 0,
      //   key: 'RINITIATED_PROCESS',
      // },
      // {
      //   name: 'Refunded',
      //   subLink: '/refundedorders',
      //   count: 0,
      //   key: 'REFUNDED',
      // },
    ],
  },
  {
    name: 'Shops',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/shop.svg',
    activeIcon: '/assets/images/menu/shop1.svg',
    subMenu: [
      { name: 'Add shop', subLink: '/addshop' },
      {
        name: 'Shops approval list',
        subLink: '/shopsapprovallist',
        count: 0,
        key: 'SHOP_APPROVAL',
      },
      { name: 'Shops list', subLink: '/shopslist' },
      // { name: 'Delivery zone', subLink: '/deliveryzone' },
    ],
  },
  // {
  //   name: 'Delivery Person',
  //   isCollapsible: true,
  //   open: false,
  //   active: false,
  //   normalIcon: '/assets/images/menu/bus.svg',
  //   activeIcon: '/assets/images/menu/bus1.svg',
  //   subMenu: [
  //     { name: 'Add delivery person', subLink: '/adddeliveryperson' },
  //     {
  //       name: 'Verification pending',
  //       subLink: '/verificationpending',
  //       count: 0,
  //       key: 'DELIVERY_APPROVAL',
  //     },
  //     {
  //       name: 'Rejected delivery persons',
  //       subLink: '/deliverypersonsrejectedlist',
  //     },
  //     { name: 'Delivery person list', subLink: '/deliverypersonlist' },
  //   ],
  // },
  {
    name: 'Products',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/doc.svg',
    activeIcon: '/assets/images/menu/doc1.svg',
    subMenu: [
      { name: 'Category approval list', subLink: '/productCategoryApprovalList' },
      { name: 'Category list', subLink: '/productcategory' },
      { name: 'Add products', subLink: '/addproducts' },
      {
        name: 'Products approval',
        subLink: '/productsapprovallist',
        count: 0,
        key: 'PRODUCT_APPROVAL',
      },
      { name: 'Products list', subLink: '/productslist' },
    ],
  },
  {
    name: 'Customers',
    isCollapsible: false,
    open: false,
    link: '/customerslist',
    active: false,
    normalIcon: '/assets/images/menu/person.svg',
    activeIcon: '/assets/images/menu/person1.svg',
  },
  // {
  //   name: 'Ads and Banners',
  //   isCollapsible: true,
  //   open: false,
  //   active: false,
  //   normalIcon: '/assets/images/menu/ad.svg',
  //   activeIcon: '/assets/images/menu/ad1.svg',
  //   subMenu: [
  //     { name: 'Ads and banners', subLink: '/adsandbanners' },
  //     { name: 'Shop Ads and banners', subLink: '/shopadsandbanners' },
  //   ],
  // },
  {
    name: 'Ads and Banners',
    isCollapsible: false,
    open: false,
    link: '/adsandbanners',
    active: false,
    normalIcon: '/assets/images/menu/ad.svg',
    activeIcon: '/assets/images/menu/ad1.svg',
  },
  {
    name: 'Coupons',
    isCollapsible: false,
    open: false,
    link: '/coupons',
    active: false,
    normalIcon: '/assets/images/menu/coupon.svg',
    activeIcon: '/assets/images/menu/coupon1.svg',
  },
  {
    name: 'Earnings',
    isCollapsible: false,
    open: false,
    active: false,
    link: '/earnings',
    normalIcon: '/assets/images/menu/wallet.svg',
    activeIcon: '/assets/images/menu/wallet1.svg',
  },
  {
    name: 'Payouts',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/wallet.svg',
    activeIcon: '/assets/images/menu/wallet1.svg',
    subMenu: [
      { name: 'Customer payouts', subLink: '/customerpayouts' },
      { name: 'Shop payouts', subLink: '/shoppayouts' },
      // { name: 'Delivery payouts', subLink: '/deliverypayouts' },
      // { name: 'Collect cash', subLink: '/collectcash' },
    ],
  },
  {
    name: 'Grievance',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/message.svg',
    activeIcon: '/assets/images/menu/message1.svg',
    subMenu: [
      {
        name: 'Customer grievance',
        subLink: '/customergrievance',
        count: 0,
        key: 'CUSTOMER_ENQUIRY',
      },
      {
        name: 'Shop grievance',
        subLink: '/shopgrievance',
        count: 0,
        key: 'SHOP_ENQUIRY',
      },
      // {
      //   name: 'Delivery grievance',
      //   subLink: '/deliverygrievance',
      //   count: 0,
      //   key: 'DELIVERY_ENQUIRY',
      // },
    ],
  },
  {
    name: 'Settings',
    isCollapsible: true,
    open: false,
    active: false,
    normalIcon: '/assets/images/menu/setting.svg',
    activeIcon: '/assets/images/menu/setting1.svg',
    subMenu: [
      { name: 'Push notifications', subLink: '/pushnotification' },
      { name: 'Contact details', subLink: '/contactdetails' },
      // { name: 'Delivery charge', subLink: '/deliverycharge' },
      { name: 'Vendors charge', subLink: '/vendorscharge' },
      { name: 'Manager', subLink: '/manager' },
    ],
  },
]

export default list
